### PR TITLE
Dp container copy

### PR DESCRIPTION
**Pull request by bocchino**
Fixes to DP container copying, as discussed. Note that a small change to FPP code gen is required. For now I have hand-coded the workarounds and marked them with TODOs.

### CODE REVIEW

**Comment by bocchino** [comment]
@LeStarch FYI.

**Comment by timcanham** [comment]
So the `DpContainer::copyMembersFrom()` is a temporary measure until there is new FPP?

**Comment by bocchino** [comment]
When there's new FPP code gen, these lines will go away:

https://github.com/bocchino/fprime/blob/43885911748eb6369e66809064bde6ac61da5c71/Ref/SignalGen/SignalGen.cpp#L283-L284

**Comment by bocchino** [comment]
I'm proposing to keep the `copyMembersFrom` syntax. As discussed, it's more explicit about what's going on than an overloaded `operator=`.

**Comment by timcanham** [comment]
I thought that was just for the underlying `ExternalSerializeBuffer`. I think the container should have an `=` operator.

**Comment by bocchino** [comment]
OK, when I update the FPP code gen I can add a protected operator= in the base class and add a public operator= in the derived class that calls it. I don't want to add a public operator= in the base class -- that's contrary to C++ coding rules.

**Comment by bocchino** [comment]
Closing in favor of #20.

**Pull request closed without merging**
